name = "haakonRegistry"
uuid = "c2c46d28-3be2-4358-9c6d-3dfe6508e42e"
repo = "https://github.com/haakon-e/haakonRegistry.jl.git"
description = "Registry for unregistered seismic dependencies"

[packages]
436b0209-26ab-4e65-94a9-6526d86fea76 = { name = "NaturalEarth", path = "N/NaturalEarth" }
b372bb87-02dd-52bb-bcf6-c30dd83fd342 = { name = "SeisIO", path = "S/SeisIO" }
c96ba436-a6fe-11e9-10ab-c9f3919c93d1 = { name = "GeographicLib", path = "G/GeographicLib" }
